#!/usr/bin/env python3

import numpy as np
from scipy.sparse import csr_matrix
from flask import Flask
from flask import Response
from flask import request, jsonify
import pandas as pd
from joblib import dump, load

app = Flask(__name__)


PATHS = {
    'hyperparameters': 'input/config/hyperparameters.json',
    'input': 'input/config/inputdataconfig.json',
    'data': 'input/data/',
    'model': 'model/'
}

def get_path(key):
    return '/opt/ml/' + PATHS[key]
    

def load_model():
    model = None
    
    filename = get_path('model') + 'model'
    print(filename)
    
    model = load(filename)
    return model


def load_training_data():
    interactions = pd.read_csv('/opt/ml/input/data/train/interactions.csv')
    
    user_interaction = pd.pivot_table(interactions, 
                                  index='user_id', 
                                  columns='quest_id', values='rating')

    user_interaction = user_interaction.fillna(0)
    
    user_id = list(user_interaction.index)
    user_dict = {}
    counter = 0 
    
    for i in user_id:
        user_dict[i] = counter
        counter += 1

    return user_interaction, user_dict


@app.route("/predict", methods=["POST"])
def predict():
    
    model = load_model()
    post_body = request.json
    
    user_id = post_body['user_id']
    n_items=post_body['n_items']
    
    scores = model.predict(user_id, np.arange(n_items))
    
    scores = jsonify(scores.tolist())
    return Response(response= scores, status=200)


@app.route("/ping")
def ping():
    return Response(response="OK", status=200)


app.run(host="0.0.0.0", port=8080)
